### ISSUE TITLE
Learn about git and do pull requests

### ISSUE THREAD

**Issue by weiqingtoh** [moexmen/foosball-leaderboard#5]
As above.

**Comment by weiqingtoh** [comment]
#4

**Comment by weiqingtoh** [comment]
@moexmen/interns please note

**Comment by chesterhow** [comment]
K

**Comment by ivantjh** [comment]
Okay



On April 6, 2016 at 3:02:33 PM, Weiqing (notifications@github.com) wrote:

@moexmen/interns please note
